### ISSUE TITLE
GetCoordinates is missing from the Code

### ISSUE THREAD

**Issue by ab-valtira** [Cyash/Pothole_Detection#1]
import GetCoordinates references a module that doesn't exist in the repo.

`[2019-05-07 13:55:25 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/program/wsgi.py", line 1, in <module>
    import predictor as myapp
  File "/opt/program/predictor.py", line 25, in <module>
    from video_markup import flask_process_video
  File "/opt/program/video_markup.py", line 31, in <module>
    import GetCoordinates
ImportError: No module named 'GetCoordinates'
[2019-05-07 13:55:25 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.5/dist-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/opt/program/wsgi.py", line 1, in <module>
    import predictor as myapp
  File "/opt/program/predictor.py", line 25, in <module>
    from video_markup import flask_process_video
  File "/opt/program/video_markup.py", line 31, in <module>
    import GetCoordinates
ImportError: No module named 'GetCoordinates'
`

**Comment by Cyash** [comment]
@ab-valtira you can take off that import as I was using it for some OCR work on image while testing, looks like I missed to push it nevertheless you don't need it

**Comment by Cyash** [comment]
I'm closing this issue, please open it again if you need any help on this
